/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ftjtlafoxcgohsphbfng"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0anRsYWZveGNnb2hzcGhiZm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NjEzMTAsImV4cCI6MjA5MzEzNzMxMH0.i-xuITJtudNXG-T0k7wP0thncphYIsTMH6061mE0fpk"